# Generated by Django 5.2 on 2025-04-30 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='note',
            name='plant',
        ),
        migrations.DeleteModel(
            name='Garden',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
