# Generated by Django 5.2 on 2025-04-30 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardening', '0002_remove_plant_garden_remove_note_plant_delete_garden_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte název zahrádky', max_length=100, verbose_name='Název zahrádky')),
                ('description', models.TextField(blank=True, help_text='Zadejte popis zahrádky (volitelné)', null=True, verbose_name='Popis zahrádky')),
                ('image', models.ImageField(blank=True, help_text='Nahrajte obrázek zahrádky (volitelné)', null=True, upload_to='gardens/', verbose_name='Obrázek zahrádky')),
                ('owner', models.ForeignKey(help_text='Vyberte vlastníka zahrádky', on_delete=django.db.models.deletion.CASCADE, related_name='owned_gardens', to=settings.AUTH_USER_MODEL, verbose_name='Vlastník zahrádky')),
                ('users_with_access', models.ManyToManyField(blank=True, help_text='Vyberte uživatele, kteří mají přístup k zahrádce', related_name='accessible_gardens', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelé s přístupem')),
            ],
            options={
                'verbose_name': 'Zahrádka',
                'verbose_name_plural': 'Zahrádky',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte název rostliny', max_length=100, verbose_name='Název rostliny')),
                ('planted_date', models.DateField(blank=True, help_text='Zadejte datum, kdy byla rostlina zasazena (volitelné)', null=True, verbose_name='Datum zasazení')),
                ('image', models.ImageField(blank=True, help_text='Nahrajte obrázek rostliny (volitelné)', null=True, upload_to='plants/', verbose_name='Obrázek rostliny')),
                ('garden', models.ForeignKey(help_text='Vyberte zahrádku, do které rostlina patří', on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='gardening.garden', verbose_name='Zahrádka')),
            ],
            options={
                'verbose_name': 'Rostlina',
                'verbose_name_plural': 'Rostliny',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='Datum, kdy byla poznámka vytvořena', verbose_name='Datum poznámky')),
                ('content', models.TextField(help_text='Zadejte obsah poznámky', verbose_name='Obsah poznámky')),
                ('image', models.ImageField(blank=True, help_text='Nahrajte obrázek k poznámce (volitelné)', null=True, upload_to='notes/', verbose_name='Obrázek poznámky')),
                ('plant', models.ManyToManyField(help_text='Vyberte rostliny, ke kterým poznámka patří', related_name='notes', to='gardening.plant', verbose_name='Rostliny')),
            ],
            options={
                'verbose_name': 'Poznámka',
                'verbose_name_plural': 'Poznámky',
                'ordering': ['-date'],
            },
        ),
    ]
