# Generated by Django 5.2 on 2025-04-30 10:48

import django.db.models.deletion
import gardening.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='planted_date',
            field=models.DateField(blank=True, help_text='Zadejte datum, kdy byla rostlina zasazena (volitelné)', null=True, validators=[gardening.models.validate_not_future_date], verbose_name='Datum zasazení'),
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(help_text='Zadejte doporučení pro rostlinu', verbose_name='Doporučení')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datum, kdy bylo doporučení vytvořeno', verbose_name='Datum vytvoření')),
                ('plant', models.ForeignKey(help_text='Vyberte rostlinu, ke které doporučení patří', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='gardening.plant', verbose_name='Rostlina')),
            ],
            options={
                'verbose_name': 'AI Doporučení',
                'verbose_name_plural': 'AI Doporučení',
                'ordering': ['-created_at'],
            },
        ),
    ]
