# Generated by Django 5.2 on 2025-04-30 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardening', '0004_alter_plant_planted_date_airecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zadejte typ rostliny (např. Rajčata, Mrkev)', max_length=100, unique=True, verbose_name='Typ rostliny')),
            ],
            options={
                'verbose_name': 'Typ rostliny',
                'verbose_name_plural': 'Typy rostlin',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type',
            field=models.ForeignKey(blank=True, help_text='Vyberte typ rostliny (volitelné)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plants', to='gardening.planttype', verbose_name='Typ rostliny'),
        ),
    ]
